kind: Deployment
apiVersion: apps/v1
metadata:
  name: dotnet
  namespace: binaryit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
        - name: dotnet
          image: renderman/dotnet:2
          resources:
            requests:
              memory: "64Mi"
              cpu: "30m"
            limits:
              memory: "2048Mi"
              cpu: "1"
          stdin: true 
          tty: true 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
      