kind: Service
apiVersion: v1
metadata:
  name: dotnet-service
  namespace: binaryit
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30081
      port: 8080
      targetPort: 8080
      protocol: TCP
    # - name: httpsk
    #   port: 443
    #   targetPort: 3002 
    #   protocol: TCP
  selector:
    app: dotnet